### ISSUE TITLE
Fix Bugs: Difficulty in blocks

### ISSUE THREAD

**Issue by tbrand** [tbrand/SushiCoin#23]
## Content
If the difficulty is updated, easier blocks will be invalid currently.
So have to record the difficulty onto each block.

## Todo
- [ ] pass the difficulty to sushid.
- [ ] difficulty in blocks
- [ ] send node_lists for broadcasting

**Comment by tbrand** [comment]
Implement another approach, but they have been fixed.
