### ISSUE TITLE
Testnet feature

### ISSUE THREAD

**Issue by tbrand** [tbrand/SushiCoin#8]
Testnet is necessary especially for new comer or developers.

## Tasks
- [x] check when handshake
  - [x] with another node
  - [x] with another miner
- [ ] healthcheck
- [ ] check network type when create transaction
